runtime: nodejs16
service: tcc

# handlers: 
#   - url: /
#     static_files: build/index.js
#     upload: build/index.js
  
#   - url: /(.*)
#     static_files: build/\1
#     upload: build/(.*)

#   - url: /.*
#     static_dir: build 
