runtime: nodejs16
service: tcc

handlers: 
  - url: /(.*\.(js|css|ico|woff|woff2|ttf|otf|json))
    static_files: build/\1
    upload: build/.*\.(js|css|ico|woff|woff2|ttf|otf|json)

  - url: /.*
    script: auto
